version: '3'
services:
  api:
    build: ./codesearch-api
    ports:
      - "8081:8081"
    volumes:
      - "./codesearch-api:/app"
  ui:
    build: ./codesearch-ui
    ports:
      - "8080:8080"
    volumes:
      - "./codesearch-ui:/app"
    command:
      - yarn
      - serve
